# --- 定義個別角色 ---

[k3s_master]
10.1.104.10

[k3s_node]
10.1.104.11
10.1.104.12

# --- 定義大群組 (包含上面兩個小群組) ---

[martinlee_lab_vm:children]
k3s_master
k3s_node

# --- 定義該大群組共用的變數 ---

[martinlee_lab_vm:vars]
ansible_user=martinlee